#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/smoke-lib.sh"

RUNS="${RUSTLE_STRESS_BRIDGE_RUNS:-1}"
WARMUP_RUNS="${RUSTLE_STRESS_BRIDGE_WARMUP_RUNS:-0}"
CONNECTIONS="${RUSTLE_STRESS_BRIDGE_CONNECTIONS:-256}"
BODY_BYTES="${RUSTLE_STRESS_BRIDGE_BODY_BYTES:-1048576}"
TRANSPORTS="${RUSTLE_STRESS_BRIDGE_TRANSPORTS:-agent}"

smoke_info "stress: bridge lab transports=${TRANSPORTS} connections=${CONNECTIONS} body_bytes=${BODY_BYTES}"

env_args=(
  "RUSTLE_BENCH_RUNS=${RUNS}"
  "RUSTLE_BENCH_WARMUP_RUNS=${WARMUP_RUNS}"
  "RUSTLE_BENCH_CONNECTIONS=${CONNECTIONS}"
  "RUSTLE_BENCH_BODY_BYTES=${BODY_BYTES}"
  "RUSTLE_BENCH_BRIDGE_TRANSPORTS=${TRANSPORTS}"
)

if [[ -n "${RUSTLE_STRESS_MIN_AGENT_DIRECT_RATIO:-}" ]]; then
  env_args+=("RUSTLE_BENCH_MIN_AGENT_DIRECT_RATIO=${RUSTLE_STRESS_MIN_AGENT_DIRECT_RATIO}")
fi
if [[ -n "${RUSTLE_STRESS_RATIO_MIN_CONNECTIONS:-}" ]]; then
  env_args+=("RUSTLE_BENCH_RATIO_MIN_CONNECTIONS=${RUSTLE_STRESS_RATIO_MIN_CONNECTIONS}")
fi
if [[ -n "${RUSTLE_STRESS_AGENT_SESSIONS:-}" ]]; then
  env_args+=("RUSTLE_BENCH_AGENT_SESSIONS=${RUSTLE_STRESS_AGENT_SESSIONS}")
fi
if [[ -n "${RUSTLE_STRESS_AGENT_COMMAND:-}" ]]; then
  env_args+=("RUSTLE_BENCH_AGENT_COMMAND=${RUSTLE_STRESS_AGENT_COMMAND}")
fi

env "${env_args[@]}" "${SCRIPT_DIR}/bench-bridge-lab.sh"
